version: '3.8'

services:
  redis-server:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379" 
    networks:
      - redis-net

  subscriber:
    build: /listener
    container_name: python-sub
    command: python listener.py
    depends_on:
      - redis-server
    networks:
      - redis-net
    restart: on-failure

  publisher:
    build: /sender
    container_name: python-pub
    command: python sender.py
    depends_on:
      - redis-server
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge